export const ANALYTICS_EVENT_TYPES = {
  STORY_CREATED: "STORY_CREATED",
  SCRIPT_GENERATED: "SCRIPT_GENERATED",
  SCRIPT_VIEW: "SCRIPT_VIEW",
  SCRIPT_SAVE: "SCRIPT_SAVE",
  MESSAGE_SENT: "MESSAGE_SENT",
  PITCH_SENT: "PITCH_SENT",
  PROFILE_VIEW: "PROFILE_VIEW",
  FOLLOW_WRITER: "FOLLOW_WRITER",
};

export const ANALYTICS_EVENT_TYPE_SET = new Set(Object.values(ANALYTICS_EVENT_TYPES));

export const ANALYTICS_AUDIENCES = {
  WRITER: "writer",
  PRODUCER: "producer",
};

export const DEFAULT_ANALYTICS_DAYS = 30;
